services:
  api:
    image: 540551285630.dkr.ecr.us-east-1.amazonaws.com/test:latest
    ports:
      - "80:80"
    volumes:
      - /mnt/efs/json-storage:/mnt/efs/json-storage
    environment:
      - STORAGE_PATH=/mnt/efs/json-storage
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s